config/routes.rb
Rails.application.routes.draw do
  resources :genders
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users
  root 'static_pages#index'

  # resources :payments
  resources :applications
  resources :lodgings
  resources :workshops

  resources :application_settings

  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/privacy', to: 'static_pages#privacy'
  get '/terms_of_service', to: 'static_pages#terms_of_use'
  get '/conference_closed', to: 'static_pages#conference_closed'
  get '/conference_full', to: 'static_pages#conference_full'
  get '/accept_offer', to: 'static_pages#accept_offer'
  get '/subscription', to: 'applications#subscription'

  get 'payments', to: 'payments#index'
  get 'payment_receipt', to: 'payments#payment_receipt'
  post 'payment_receipt', to: 'payments#payment_receipt' # needed to address PCI gateway rqrmts
  get 'payment_show', to: 'payments#payment_show', as: 'all_payments'
  get 'make_payment', to: 'payments#make_payment'
  post 'make_payment', to: 'payments#make_payment'

  post 'run_lotto', to: 'application_settings#run_lottery'

  post '/send_offer/:id', to: 'application_settings#send_offer', as: 'send_offer'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  # before_action :current_application_open?, only: [:index]

  def index
    redirect_to conference_closed_url unless current_application_open?
  end

  def about
  end

  def contact
  end

  def privacy
  end

  def terms_of_use
  end

  def conference_closed
  end

  def conference_full
  end

  def accept_offer
    if current_application_open? 
      redirect_to root_url
    end
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.haml
- provide(:title, 'About')

%h1 The Bear River Conference
%h6
  The Bear River Writers' Conference is defined by its own particular geography,
  situated as it is at the intersection of the natural and creative worlds.
  Populated by an eclectic collection of writers of all levels of experience,
  it offers community members a hiatus from daily routine and the chance to
  find a space for themselves and their words.

  %em
    Find your place at Bear River.
  =link_to '...more','https://lsa.umich.edu/bearriver/'
%h6 This portal is for registrants to submit their payments.

app/views/static_pages/accept_offer.haml
- provide(:title, 'Congratulations on your Offer')

%h1 
  = "Congratulation on being selected to attend the #{current_application_settings.contest_year} Bear River Conference!"
%p
  = link_to "Login", new_user_session_path, :class => 'btn btn-sm btn-success'
%h4
  Dear Writer:
  %br
  = current_application_settings.registration_acceptance_directions
  %br
  %br
  Thank you.
  %br
  The Bear River Staff

app/views/static_pages/conference_closed.html.haml
- provide(:title, 'Conference Information')

%p
  Dear Writers:
  %br
  - if current_application_settings.opendate > Time.now
    = "Registration for the #{current_application_settings.contest_year} conference will be open:"
    %p.m-3
      = current_application_settings.opendate.to_s(:special_date)
      until
      = (current_application_settings.opendate + 2.days).to_s(:special_date)
    Please return to the
    = link_to "registration page", root_url
    after that date and time.

  - else
    -if user_signed_in? && user_has_application?(current_user)
      - if ["registration_offered", "registration_accepted"].include? Application.active_conference_applications.find_by(user_id: current_user).offer_status
        - if !user_has_payments?(current_user)
          %p
            To accept your offer  
            = button_to "Pay the Application Fee", make_payment_path(amount: current_application_settings.registration_fee), class: 'btn btn-success'
        - else
          %p
            You may use the links in the 'Your Details' box to the right to view or manage your payments.
      - else
        - if current_application_settings.application_closed_directions.present?
          = current_application_settings.application_closed_directions
    - else
      - if current_application_settings.application_closed_directions.present?
        = current_application_settings.application_closed_directions

  %br
  %br
  Thank you.
  %br
  The Bear River Staff

app/views/static_pages/contact.html.haml
- provide(:title, 'Contact')

%h1 Contact Us
%p
  Contact Us
  Bear River Writers’ Conference
  Dept. of English Language & Literature
  3187 Angell Hall, University of Michigan
  435 South State Street
  Ann Arbor, MI 48109-1003
  Fax: 734.763.3128

  Find Bear River on Facebook

  Questions? Email us at
  = mail_to bearriver-questions@umich.edu

app/views/static_pages/index.html.haml
- provide(:title, 'Home')

%h1 Bear River Conference Registration
%h6.pl-3.text-muted
  = "Time Now #{Time.now.to_s(:special_date)}"

- if current_application_settings.application_open_directions.present?
  = current_application_settings.application_open_directions
  %br
  %br

.card.text-center
  .card-header
    The window for registering to attend the Bear River Conference will be open
    for
    = current_application_settings.application_open_period
    hours
  .card-body
    Starting:
    = current_application_settings.opendate.to_s(:special_date)
    %br
    Ending:
    = (current_application_settings.opendate + current_application_settings.application_open_period.hours).to_s(:special_date)

  .card-footer

    - if user_signed_in?
      - if user_has_application?(current_user)
        %h6.alert.alert-success
          You have successfully filled out an application for this year's conference. We will
          contact you soon with further instructions.
        %br
          Return to the
          = link_to "Bear River Conference site", "https://lsa.umich.edu/bearriver"
      - else
        .row.justify-content-center
          .col-2
            = link_to 'Apply', new_application_path, class: 'btn btn-sm btn-success'
    - else
      %h6
        You are required to have an account to register for
        the conference.
        %br
        = link_to "Login", new_user_session_path, class: 'btn btn-sm btn-info'
        or
        = link_to "Sign up", new_user_registration_path, class: 'btn btn-sm btn-primary'

app/views/static_pages/privacy.html.haml
- provide(:title, 'Privacy Statement')

%h1 Website Privacy Notice
%h4 Overview

%h6 The University of Michigan recognizes and values the privacy of the university community members and its guests, and strives to be the leaders and best in the ways in which we manage your personal information. This value is reflected in Regent’s Bylaw Sec. 14.07. Privacy and Access to Information, which states in part:

%p.blockquote “In collecting, utilizing, and releasing information about individuals associated with the university, the university will strive to protect individual privacy, to use information only for the purpose for which it was collected, and to inform individuals of the personal information about them that is being collected, used, or released.”

%h6 In principle, the University of Michigan strives to:

%ul
  %li Collect, store, and use the minimum amount of personal information that is necessary for its legitimate business purposes, and to comply with legal obligations.
  %li Take reasonable steps to ensure the personal information we manage is accurate and up-to-date.
  %li Limit who has access to the personal information in our possession to only those who need it for a legitimate, specific purpose.
  %li Protect personal information through appropriate physical and technical security measures tailored to the sensitivity of the personal data we hold.
  %li Communicate with our students, faculty, employees, suppliers, partners, and others about how we use personal information in our day-to-day operations.
  %li Provide opportunities to control your personal information, as permitted by applicable United States and other laws.
  %li Integrate privacy in the design of our activities when that involves the use of personal data.

%p
  The full content of the
  = link_to 'U-M Website Privacy Notice', 'https://umich.edu/about/privacy/'

app/views/static_pages/terms_of_use.html.haml
- provide(:title, 'Terms of Use')
.container
  %h1 U-M Network Responsible Use Agreement
  %h6 Access to the University of Michigan’s networks is provided in support of students’ academic and research activities, as well as reasonable and appropriate personal use.

  %h6
    Read the information
    = link_to 'here', 'https://its.umich.edu/enterprise/wifi-networks/network-responsible-use-agreement'
    carefully as it specifies user responsibilities and responsible use standards for connecting to computer networks, including those in residence halls and Northwood Apartments.

  %h6
    You must agree to the terms and conditions outlined
    = link_to 'here', 'https://its.umich.edu/enterprise/wifi-networks/network-responsible-use-agreement'
    to use the networks.