config/routes.rb
Rails.application.routes.draw do
  resources :genders
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users
  root 'static_pages#index'

  # resources :payments
  resources :applications
  resources :lodgings
  resources :workshops

  resources :application_settings

  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/privacy', to: 'static_pages#privacy'
  get '/terms_of_service', to: 'static_pages#terms_of_use'
  get '/conference_closed', to: 'static_pages#conference_closed'
  get '/conference_full', to: 'static_pages#conference_full'
  get '/accept_offer', to: 'static_pages#accept_offer'
  get '/subscription', to: 'applications#subscription'

  get 'payments', to: 'payments#index'
  get 'payment_receipt', to: 'payments#payment_receipt'
  post 'payment_receipt', to: 'payments#payment_receipt' # needed to address PCI gateway rqrmts
  get 'payment_show', to: 'payments#payment_show', as: 'all_payments'
  get 'make_payment', to: 'payments#make_payment'
  post 'make_payment', to: 'payments#make_payment'

  post 'run_lotto', to: 'application_settings#run_lottery'

  post '/send_offer/:id', to: 'application_settings#send_offer', as: 'send_offer'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/application.rb
# == Schema Information
#
# Table name: applications
#
#  id                             :bigint           not null, primary key
#  first_name                     :string
#  last_name                      :string
#  gender                         :string
#  birth_year                     :integer
#  street                         :string
#  street2                        :string
#  city                           :string
#  state                          :string
#  zip                            :string
#  country                        :string
#  phone                          :string
#  email                          :string
#  email_confirmation             :string
#  workshop_selection1            :string
#  workshop_selection2            :string
#  workshop_selection3            :string
#  lodging_selection              :string
#  partner_registration_selection :string
#  partner_first_name             :string
#  partner_last_name              :string
#  how_did_you_hear               :string
#  accessibility_requirements     :text
#  special_lodging_request        :text
#  food_restrictions              :text
#  user_id                        :bigint
#  created_at                     :datetime         not null
#  updated_at                     :datetime         not null
#  conf_year                      :integer
#  lottery_position               :integer
#  offer_status                   :string
#  result_email_sent              :boolean          default(FALSE), not null
#  offer_status_date              :datetime
#  subscription                   :boolean          default(FALSE)
#
class Application < ApplicationRecord
  before_create :set_contest_year

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :gender, presence: true
  validates :birth_year, presence: true
  validates :street, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zip, presence: true
  validates :country, presence: true
  validates :phone, presence: true
  validates :email, presence: true, uniqapplication: true
  validates :workshop_selection1, presence: true
  validates :workshop_selection2, presence: true
  validates :workshop_selection3, presence: true
  validates :lodging_selection, presence: true
  validates :partner_registration_selection, presence: true

  HOW_DID_YOU_HEAR = ["---", "Word of Mouth", "Magazine Advertisement", "Online Advertisement", "Newspaper Advertisement", "Other"]

  belongs_to :user

  def name
    "#{first_name} #{last_name}"
  end

  def display_name
    "#{name} - #{email}"
  end

  def total_user_has_paid
    user.total_paid
  end

  def first_workshop_instructor
    Workshop.find(workshop_selection1).instructor
  end

  def second_workshop_instructor
    Workshop.find(workshop_selection2).instructor
  end

  def third_workshop_instructor
    Workshop.find(workshop_selection3).instructor
  end

  def lodging_description
    Lodging.find(lodging_selection).description
  end

  def partner_registration_description
    PartnerRegistration.find(partner_registration_selection).description
  end

  scope :active_conference_applications, -> { where("conf_year = ?", ApplicationSetting.get_current_app_settings.contest_year) }

  scope :application_accepted, -> { active_conference_applications.where("offer_status = ?", "registration_accepted") }

  scope :application_offered, -> { active_conference_applications.where("offer_status = ?", "registration_offered") }

  private

  def set_contest_year
    self.conf_year = ApplicationSetting.get_current_app_settings.contest_year
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  private

  def current_application_settings
    @current_application_settings ||= ApplicationSetting.get_current_app_settings
  end

    helper_method :current_application_settings

    def current_application_open?
      if current_application_settings
        application_opens = current_application_settings.opendate
        range = application_opens..(application_opens + 2.days)
        range.include?(Time.now)
      end
    end

    helper_method :current_application_open?

    def user_has_application?(user)
      if Application.active_conference_applications.find_by(user_id: user).nil?
        false
      else
        true
      end
    end

    helper_method :user_has_application?

    def user_has_payments?(user)
      # return true unless Payment.find_by(user_id: user).nil?
      if Payment.current_conference_payments.find_by(user_id: user).nil?
        false
      else
        true
      end
    end

    helper_method :user_has_payments?

    def payments_open?
      current_application_settings.allow_payments
    end

    helper_method :payments_open?

end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController

  before_action :authenticate_user!
  before_action :set_application, only: [:show, :edit, :update, :destroy]
  before_action :get_lodgings
  before_action :get_partner_registrations
  # before_action :contest_is_closed?, only: [:new]

  # GET /applications
  # GET /applications.json
  def index
    redirect_to root_url
  end

  # GET /applications/1
  # GET /applications/1.json
  def show
    cost_lodging = Lodging.find_by(description: @application.lodging_selection).cost.to_f
    cost_partner = PartnerRegistration.find_by(description: @application.partner_registration_selection).cost.to_f
    @total_cost = cost_lodging + cost_partner
  end

  # GET /applications/new
  def new
    @application = Application.new
  end

  # GET /applications/1/edit
  def edit
    redirect_to root_path unless @application.offer_status.blank?
  end

  # POST /applications
  # POST /applications.json
  def create
    @application = Application.new(application_params)
    @application.email = current_user.email
    @application.user = current_user
    respond_to do |format|
      if @application.save
        format.html { redirect_to @application, notice: 'Confirm Your Application Details.' }
        format.json { render :show, status: :created, location: @application }
      else
        format.html { render :new }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /applications/1
  # PATCH/PUT /applications/1.json
  def update
    respond_to do |format|
      if @application.update(application_params)
        if params[:update_subscription] == 'update'
          format.html { redirect_to all_payments_path, notice: 'Subscription was updated.' }
          format.json { render :show, status: :ok, location: all_payments_path }
        else
          format.html { redirect_to @application, notice: 'Application was successfully updated.' }
          format.json { render :show, status: :ok, location: @application }
        end
      else
        format.html { render :edit }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /applications/1
  # DELETE /applications/1.json
  def destroy
    @application.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Application was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  def subscription 
    @application = Application.active_conference_applications.find_by(user_id: current_user)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_application
      @application = Application.find(params[:id])
      redirect_to root_url, alert: 'Not Authorized!' unless @application.user === current_user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def application_params
      params.require(:application).permit(:first_name, :last_name, :gender, :birth_year, :street, :street2, :city, :state, :zip, :country, :phone, :email, :email_confirmation, :workshop_selection1, :workshop_selection2, :workshop_selection3, :lodging_selection, :partner_registration_selection, :partner_first_name, :partner_last_name, :how_did_you_hear, :accessibility_requirements, :special_lodging_request, :food_restrictions, :user_id, :subscription)
    end

    def get_lodgings
      @lodgings = Lodging.all
    end

    def get_partner_registrations
      @partner_registrations = PartnerRegistration.all.order(cost: :asc)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Bear River Application"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end

  def offer_status 
    [
      ['Registration Offered','registration_offered'],
      ['Registration Accepted','registration_accepted'],
      ['Registration Declined','registration_declined'],
      ['Not Offered','not_offered']
    ]
  end

  def us_states
  [
    ['Select', ''],
    ['Alabama', 'AL'],
    ['Alaska', 'AK'],
    ['Arizona', 'AZ'],
    ['Arkansas', 'AR'],
    ['California', 'CA'],
    ['Colorado', 'CO'],
    ['Connecticut', 'CT'],
    ['Delaware', 'DE'],
    ['District of Columbia', 'DC'],
    ['Florida', 'FL'],
    ['Georgia', 'GA'],
    ['Hawaii', 'HI'],
    ['Idaho', 'ID'],
    ['Illinois', 'IL'],
    ['Indiana', 'IN'],
    ['Iowa', 'IA'],
    ['Kansas', 'KS'],
    ['Kentucky', 'KY'],
    ['Louisiana', 'LA'],
    ['Maine', 'ME'],
    ['Maryland', 'MD'],
    ['Massachusetts', 'MA'],
    ['Michigan', 'MI'],
    ['Minnesota', 'MN'],
    ['Mississippi', 'MS'],
    ['Missouri', 'MO'],
    ['Montana', 'MT'],
    ['Nebraska', 'NE'],
    ['Nevada', 'NV'],
    ['New Hampshire', 'NH'],
    ['New Jersey', 'NJ'],
    ['New Mexico', 'NM'],
    ['New York', 'NY'],
    ['North Carolina', 'NC'],
    ['North Dakota', 'ND'],
    ['Ohio', 'OH'],
    ['Oklahoma', 'OK'],
    ['Oregon', 'OR'],
    ['Pennsylvania', 'PA'],
    ['Puerto Rico', 'PR'],
    ['Rhode Island', 'RI'],
    ['South Carolina', 'SC'],
    ['South Dakota', 'SD'],
    ['Tennessee', 'TN'],
    ['Texas', 'TX'],
    ['Utah', 'UT'],
    ['Vermont', 'VT'],
    ['Virginia', 'VA'],
    ['Washington', 'WA'],
    ['West Virginia', 'WV'],
    ['Wisconsin', 'WI'],
    ['Wyoming', 'WY'],
    ['*Non-US*', 'non-us']
  ]
end

end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/views/applications/_form.html.haml
%hr
%h5 Lodging Options:
/ %h6 NOTE: Prices below include a required $100 deposit.
%hr.w-75
%h5
  Plan A:
  %small.text-muted Includes tuition, lodging and all meals. Lodging options and pricing for Plan A are listed below.
%ul
  - @lodgings.each do | lodge |
    - if lodge.plan == 'A'
      %li.font-weight-bold
        = "#{lodge.description} ( #{number_to_currency(lodge.cost.to_f)} )"
      - if lodge.description.include?("Semi-Private")
        .text-muted.ml-2 Queen Bed/Shared Bath with 1-3 others
      - if lodge.description.include?("Bunk")
        .text-muted.ml-2 Single bunk bed in a 4-bunk bedroom shared with 1-3 others/shared bath with 1-3 others
%h5
  Plan B:
  %small.text-muted Includes tuition and all meals, but not lodging for those who live in the Petoskey area. In addition, there are many hotels and motels available within twenty minutes of the conference for those who prefer greater privacy
%ul
  - @lodgings.each do | lodge |
    - if lodge.plan == 'B'
      %li.font-weight-bold
        = "#{lodge.description} ( #{number_to_currency(lodge.cost.to_f)} )"
%hr.w-75
%h5
  Attending with a spouse/partner:
  %small.text-muted
    It is possible to include a spouse/partner when registering for any of the options in Plan A or B for an
    %mark additional fee:
%ul
  - @partner_registrations.each do |pr|
    - if pr.cost > 0.0
      %li.font-weight-bold
        = "#{pr.description} ( #{number_to_currency(pr.cost.to_f)} )"
%p
  Please do not register your spouse/partner separately unless they also wish
  to attend the worshops. If your spouse/partner does want to attend the
  workshops they will need to register separately. We also highly recommend
  the "Private Room, Private Bath" option if you intend to bring your
  spouse/partner.

%hr.w-75
%h5
  Register early to secure your workshop choice:
  %small.text-muted Workshops will be assigned on a first come first serve basis. In the unlikely event of a workshop cancellation, your entire payment will be refunded upon request if you do not wish to enroll in an alternate workshop.

= form_for @application do |f|
  - if @application.errors.any?
    #error_explanation
      %h2= "#{pluralize(@application.errors.count, "error")} prohibited this application from being saved:"
      %ul
        - @application.errors.full_messages.each do |message|
          %li= message

  %br
  %h5 Registrant Details:
  %hr
  .form-group.row
    = f.label :first_name, class: 'col-sm-3 col-form-label required'
    .col-sm-9
      = f.text_field :first_name, autofocus: true, class: 'form-control'
  .form-group.row
    = f.label :last_name, class: 'col-sm-3 col-form-label required'
    .col-sm-9
      = f.text_field :last_name, class: 'form-control'
  .form-group.row
    = f.label :gender, class: 'col-sm-4 col-form-label required'
    = f.collection_select(:gender, Gender.all, :name, :name, prompt: "Pick one")
  .form-group.row
    = f.label :birth_year, 'Year of Birth', class: 'col-sm-3 col-form-label required'
    .col-sm-9
      = f.number_field :birth_year, class: 'form-control'

  %h5 Mailing Address:
  %hr
  .form-group.row
    = f.label :street, class: 'col-sm-3 col-form-label required'
    .col-sm-9
      = f.text_field :street, class: 'form-control'
  .form-group.row
    = f.label :street2, class: 'col-sm-3 col-form-label'
    .col-sm-9
      = f.text_field :street2, class: 'form-control'
  .form-group.row
    = f.label :city, class: 'col-sm-3 col-form-label required'
    .col-sm-9
      = f.text_field :city, class: 'form-control'
  .form-group.row
    = f.label :state, class: 'col-sm-3 col-form-label required'
    .col-sm-9
      = f.select :state, us_states, {}, include_blank: "-- Please Select --", class: 'form-control'
  .form-group.row
    = f.label :zip, class: 'col-sm-3 col-form-label required'
    .col-sm-9
      = f.text_field :zip, class: 'form-control'
  .form-group.row
    = f.label :country, class: 'col-sm-3 col-form-label required'
    .col-sm-9
      = f.country_select  :country, priority_countries: ["US"], include_blank: "-- Please Select --", class: 'form-control'
  .form-group.row
    = f.label :phone, class: 'col-sm-3 col-form-label required'
    .col-sm-9
      = f.text_field :phone, class: 'form-control'

  %h5 Workshop Selection:
  %hr
  .form-group.row
    = f.label :workshop_selection1, "First Choice", class: 'col-sm-4 col-form-label required'
    = f.collection_select(:workshop_selection1, Workshop.all.order_by_lastname, :instructor, :instructor,
                          prompt: "Pick one")
  .form-group.row
    = f.label :workshop_selection2, "Second Choice", class: 'col-sm-4 col-form-label required'
    = f.collection_select(:workshop_selection2, Workshop.all, :instructor, :instructor,
                          prompt: "Pick one")
  .form-group.row
    = f.label :workshop_selection3, "Third Choice", class: 'col-sm-4 col-form-label required'
    = f.collection_select(:workshop_selection3, Workshop.all, :instructor, :instructor,
                          prompt: "Pick one")

  %h5 Lodging Selection:
  %hr
  .h6
    = f.label 'Please select a room type:', class: 'required'
  .form-group
    = f.collection_radio_buttons(:lodging_selection, Lodging.all, :description, :description) do |b|
      .form-check
      = b.radio_button(class: "form-check-input ml-3")
      = b.label(class: "form-check-label  ml-5")

  .h6
    = f.label 'Please indicate whether your registration includes a spouse/partner:', class: 'required'
  .form-group
    = f.collection_radio_buttons(:partner_registration_selection, @partner_registrations.order(cost: :asc), :description, :description) do |b|
      .form-check
      = b.radio_button(class: "form-check-input ml-3")
      = b.label(class: "form-check-label  ml-5")

  %p.pl-3 if you are bringing a partner please enter their name:
  .form-row
    .form-group.col-4.offset-1
      = f.label :partner_first_name
      = f.text_field :partner_first_name, class: 'form-control'
    .form-group.col-4
      = f.label :partner_last_name
      = f.text_field :partner_last_name, class: 'form-control'

  %h5 Additional Information:
  %hr

  .form-group.row
    = f.label :accessibility_requirements, class: 'col-sm-3 col-form-label'
    .col-sm-9
      = f.text_area :accessibility_requirements, class: 'form-control', cols: 80
  .form-group.row
    = f.label :special_lodging_request, class: 'col-sm-3 col-form-label'
    .col-sm-9
      = f.text_area :special_lodging_request, class: 'form-control', cols: 80
  .form-group.row
    = f.label :food_restrictions, class: 'col-sm-3 col-form-label'
    .col-sm-9
      = f.text_area :food_restrictions, class: 'form-control', cols: 80
  .form-row
    .form-group
      = f.label :how_did_you_hear, "How did you hear about the Bear River Writers' Conference?"
      = f.select :how_did_you_hear, Application::HOW_DID_YOU_HEAR, prompt: "Pick one"

  .form-group.row
    = f.label "Required items are marked with an asterisk", class: 'text-muted required'

  .actions
    = f.submit 'Submit', class: 'btn btn-success'

app/views/applications/edit.html.haml
%h1 Editing application

= render 'form'

app/views/applications/index.html.haml
%h1 Listing applications

%table
  %thead
    %tr
      %th First name
      %th Last name
      %th Gender
      %th Birth year
      %th Street
      %th Street2
      %th City
      %th State
      %th Zip
      %th Country
      %th Phone
      %th Email
      %th Email confirmation
      %th Workshop selection1
      %th Workshop selection2
      %th Workshop selection3
      %th Lodging selection
      %th Partner registration selection
      %th Partner first name
      %th Partner last name
      %th How did you hear
      %th Accessibility requirements
      %th Special lodging request
      %th Food restrictions
      %th User
      %th
      %th
      %th

  %tbody
    - @applications.each do |application|
      %tr
        %td= application.first_name
        %td= application.last_name
        %td= application.gender
        %td= application.birth_year
        %td= application.street
        %td= application.street2
        %td= application.city
        %td= application.state
        %td= application.zip
        %td= application.country
        %td= application.phone
        %td= application.email
        %td= application.email_confirmation
        %td= application.workshop_selection1
        %td= application.workshop_selection2
        %td= application.workshop_selection3
        %td= application.lodging_selection
        %td= application.partner_registration_selection
        %td= application.partner_first_name
        %td= application.partner_last_name
        %td= application.how_did_you_hear
        %td= application.accessibility_requirements
        %td= application.special_lodging_request
        %td= application.food_restrictions
        %td= application.user
        %td= link_to 'Show', application
        %td= link_to 'Edit', edit_application_path(application)
        %td= link_to 'Destroy', application, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Application', new_application_path

app/views/applications/new.html.haml
%h1 Step 1

= render 'form'

%br
= link_to 'Cancel', root_path, class: 'btn btn-sm btn-light'

%hr
/ .text-center NOTE: A deposit of $100 is required to complete your registration. You can make payments via credit card only.
/ %br
/ .h6.text-center DEPOSITS ARE NON-REFUNDABLE

app/views/applications/show.html.haml
- if @application.user.payments.size < 1
  %h3 Confirm your information
- else
  %h3 Your Application
  %h6.mt-4
    Thank you for your Bear River Writers' Conference application. You will
    will recieve an email after the close of the Application Window notifiying
    if you have been admitted to the conference.
  %h6.mt-4
    If your application is accepted, in March,
    you will be emailed with your workshop and housing placement. You will also
    be sent a prompt to continue paying your conference dues at that time.
    
    %pr 
      You may email any questions to:
      = mail_to "bearriver-questions@umich.edu"

%hr.w-75
.h5 Registration Details:
%p
  %b First name:
  = @application.first_name
  %br
  %b Last name:
  = @application.last_name
  %br
  %b Gender:
  = @application.gender
  %br
  %b Birth year:
  = @application.birth_year

%hr
.h5 Mailing Address:
%p
  %b Street:
  = @application.street
  %br
  %b Street2:
  = @application.street2
  %br
  %b City:
  = @application.city
  %br
  %b State:
  = @application.state
  %br
  %b Zip:
  = @application.zip
  %br
  %b Country:
  = @application.country
  %br
  %b Phone:
  = @application.phone
  %br
  %b Email:
  = @application.email

%hr
.h5 Workshop Selections:
%p
  %b Workshops you requested:
  %ol
    %li
      = @application.workshop_selection1
    %li
      = @application.workshop_selection2
    %li
      = @application.workshop_selection3

%hr
.h5 Lodging Selection
%p
  %b Lodging selection:
  = @application.lodging_selection
  %br
  %b Partner registration selection:
  = @application.partner_registration_selection
  %br
  %b Partner first name:
  = @application.partner_first_name
  %br
  %b Partner last name:
  = @application.partner_last_name
  %br
  .h6
  %b Total cost for selected options:
  .h5
    = number_to_currency(@total_cost)

%hr
.h5 Additional Details:
%p
  %b How did you hear about the Bear River Writers' Conference?
  = @application.how_did_you_hear
  %br
  %b Accessibility requirements:
  = @application.accessibility_requirements
  %br
  %b Special lodging request:
  = @application.special_lodging_request
  %br
  %b Food restrictions:
  = @application.food_restrictions

  - if @application.subscription
    %br
    %b Subscription:
    = number_to_currency(ApplicationSetting.get_current_app_settings.subscription_cost)
%hr
- if @application.offer_status.blank?
  %h6
    NOTE:
    %small.text-muted If you need to make a correction, please use the edit
    button below to return to the form.
  = link_to 'Edit', edit_application_path(@application), class: 'btn btn-sm btn-warning'

  -# %hr
  -# = link_to 'Submit Application', root_path, class: 'btn btn-sm btn-success', notice: 'Application was submitted'

  %hr
  %h6
    Cancel Registration
    .text-muted
      If you are not prepared to submit your application at this time, please
      use the option below to cancel your registration.

  -# = link_to 'Cancel', root_path, class: 'btn btn-danger'
  = link_to 'Delete', application_path(@application), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'

- else
  %h6.mt-4
    Note: If you have any questions or would like to request a change to your
    application selections please contact the conference coordinators at
    = mail_to "bearriver-questions@umich.edu"

app/views/applications/subscription.html.haml
%h2 Michigan Quarterly Review Subscription
%p
  = current_application_settings.subscription_directions

  = form_for @application do |f|
    .h6
      = f.check_box :subscription
      = f.label 'Check to add this subscription'
    .actions
      = f.submit 'Update', class: 'btn btn-success', name: "update_subscription", value: "update"

= link_to 'Back', all_payments_path, class: "btn btn-sm btn-secondary"