config/routes.rb
Rails.application.routes.draw do
  resources :genders
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users
  root 'static_pages#index'

  # resources :payments
  resources :applications
  resources :lodgings
  resources :workshops

  resources :application_settings

  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/privacy', to: 'static_pages#privacy'
  get '/terms_of_service', to: 'static_pages#terms_of_use'
  get '/conference_closed', to: 'static_pages#conference_closed'
  get '/conference_full', to: 'static_pages#conference_full'
  get '/accept_offer', to: 'static_pages#accept_offer'
  get '/subscription', to: 'applications#subscription'

  get 'payments', to: 'payments#index'
  get 'payment_receipt', to: 'payments#payment_receipt'
  post 'payment_receipt', to: 'payments#payment_receipt' # needed to address PCI gateway rqrmts
  get 'payment_show', to: 'payments#payment_show', as: 'all_payments'
  get 'make_payment', to: 'payments#make_payment'
  post 'make_payment', to: 'payments#make_payment'

  post 'run_lotto', to: 'application_settings#run_lottery'

  post '/send_offer/:id', to: 'application_settings#send_offer', as: 'send_offer'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/gender.rb
# == Schema Information
#
# Table name: genders
#
#  id          :bigint           not null, primary key
#  name        :string           not null
#  description :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Gender < ApplicationRecord

  def display_name
    self.name # or whatever column you want
  end
end

app/controllers/genders_controller.rb
class GendersController < InheritedResources::Base

  private

    def gender_params
      params.require(:gender).permit(:name, :description)
    end

end

app/helpers/genders_helper.rb
module GendersHelper
end

app/views/genders/_form.html.haml
= form_for @gender do |f|
  - if @gender.errors.any?
    #error_explanation
      %h2= "#{pluralize(@gender.errors.count, "error")} prohibited this gender from being saved:"
      %ul
        - @gender.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_field :description
  .actions
    = f.submit 'Save'

app/views/genders/edit.html.haml
%h1 Editing gender

= render 'form'

= link_to 'Show', @gender
\|
= link_to 'Back', genders_path

app/views/genders/index.html.haml
%h1 Listing genders

%table
  %thead
    %tr
      %th Name
      %th Description
      %th
      %th
      %th

  %tbody
    - @genders.each do |gender|
      %tr
        %td= gender.name
        %td= gender.description
        %td= link_to 'Show', gender
        %td= link_to 'Edit', edit_gender_path(gender)
        %td= link_to 'Destroy', gender, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Gender', new_gender_path

app/views/genders/new.html.haml
%h1 New gender

= render 'form'

= link_to 'Back', genders_path

app/views/genders/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @gender.name
%p
  %b Description:
  = @gender.description

= link_to 'Edit', edit_gender_path(@gender)
\|
= link_to 'Back', genders_path