config/routes.rb
Rails.application.routes.draw do
  resources :genders
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users
  root 'static_pages#index'

  # resources :payments
  resources :applications
  resources :lodgings
  resources :workshops

  resources :application_settings

  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/privacy', to: 'static_pages#privacy'
  get '/terms_of_service', to: 'static_pages#terms_of_use'
  get '/conference_closed', to: 'static_pages#conference_closed'
  get '/conference_full', to: 'static_pages#conference_full'
  get '/accept_offer', to: 'static_pages#accept_offer'
  get '/subscription', to: 'applications#subscription'

  get 'payments', to: 'payments#index'
  get 'payment_receipt', to: 'payments#payment_receipt'
  post 'payment_receipt', to: 'payments#payment_receipt' # needed to address PCI gateway rqrmts
  get 'payment_show', to: 'payments#payment_show', as: 'all_payments'
  get 'make_payment', to: 'payments#make_payment'
  post 'make_payment', to: 'payments#make_payment'

  post 'run_lotto', to: 'application_settings#run_lottery'

  post '/send_offer/:id', to: 'application_settings#send_offer', as: 'send_offer'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/views/layouts/_aside.html.haml
- if user_signed_in? && user_has_application?(current_user)
  - if ["registration_offered", "registration_accepted"].include? Application.active_conference_applications.find_by(user_id: current_user).offer_status
    %aside#sidebar-layout
      .container
        %h4.text-success Your Details
        .list-group
          - if user_has_application?(current_user)
            - if user_has_payments?(current_user)
              = link_to "Payments/Receipts", all_payments_path, :class => 'list-group-item list-group-item-action'
            = link_to 'Application', application_path(Application.active_conference_applications.find_by(user_id: current_user)), :class => 'list-group-item list-group-item-action'
          = link_to 'Manage Login', edit_user_registration_path, :class => 'list-group-item list-group-item-action'
          - if !user_has_application?(current_user)
            = link_to "Submit an Application", new_application_path, :class => 'btn btn-sm btn-outline-success'
        = content_for :side

app/views/layouts/_footer.html.haml
%footer.footer.fixed-bottom
  .container-responsive
    .row.justify-content-around
      .footer-col-rt.col-3
        %a{:href => "https://lsa.umich.edu/bearriver/"}
          %span{:style => "color: rgb(255,203,5);"} Bear River Writers' Conference
      .footer-col-rt.col-4
        %i.fa.fa-map-marker
        %a{:href => "http://campusinfo.umich.edu/campusmap", :target => "_blank"}
          435 S. State Street
          %br
          %i.fa.fa-map-marker.invisible
          Room 3187
          %br
          %i.fa.fa-map-marker.invisible
          Ann Arbor, MI 48109-1003
        .email
          %i.fa.fa-envelope
          %a{:href => "bearriver-questions@umich.edu"} bearriver-questions@umich.edu

      .footer-col-lf.col-4.text-right
        %label.sr-only{:for => "deptPhone"} Click to call 734.763.2342
        #deptPhone.phone{:title => "Call New England Literature Program"}
          %i.fa.fa-phone
          734.763.2342
        .fax
          %i.fa.fa-print
          734.763.3128
        %br
        %i.fa.fa-lock
        = link_to "Admin", admin_root_path

    .row
      .copyright.col.text-center
        &copy; Regents of the University of Michigan
        = Date.today.year

app/views/layouts/_header.html.haml
%header
  .container-responsive
    %nav.navbar.navbar-expand-lg.navbar-dark.bg-dark
      = link_to image_tag(asset_pack_path('media/images/bearriver-logo.png'), alt: "Bear River Logo, link to home page.", class: 'navbar-brand', id: 'nav-bar-logo'), root_path
      %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
        %span.navbar-toggler-icon
      #navbarSupportedContent.collapse.navbar-collapse
        %ul.navbar-nav.mr-auto
          %li.nav-item
            = link_to "Home", root_path, :class => 'nav-link'
          %li.nav-item
            = link_to "About", about_path, :class => 'nav-link'
          %li.nav-item
            = link_to "Privacy", privacy_path, :class => 'nav-link'
          %li.nav-item
            = link_to "Terms of Use", terms_of_service_path, :class => 'nav-link'

        %p.navbar-text.pull-right
          - if user_signed_in?
            Logged in as
            = link_to current_user.email, edit_user_registration_path, :class => 'navbar-link'
            %br
            = link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'
          - else
            - if current_application_open?
              = link_to "Sign up", new_user_registration_path, :class => 'navbar-link'
              |
              \#{link_to "Login", new_user_session_path, :class => 'navbar-link'}
            - else 
              = link_to "Login", new_user_session_path, :class => 'navbar-link'

app/views/layouts/_notifications.html.haml
- flash.each do |key, value|
  - if key == 'alert' or key == 'notice'
    = content_tag :div, value, class: "flash #{key}"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title BearriverApplication
    = csrf_meta_tags
    = csp_meta_tag
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
  %body
    = render "layouts/header"
    = render "layouts/notifications"
    = render 'layouts/aside'
    
    .container
      = yield

      = debug(params) if Rails.env.development?
      = debug @user  if Rails.env.development?

    = render "layouts/footer"